sudo: false
language: node__js
cache:
  directories:
  - node_modules
branches:
  only:
    - master
notifications:
  email: false
node__js:
  - '12'
before_script:
  - npm prune
script:
  - npm run test
  - npm run check-coverage
  - npm run build
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"